### ISSUE TITLE
Optifine multithread chunk loading : Pbuffer creation problem

### ISSUE THREAD

**Issue by TataTawa** [longjunyu2/MCinaBox#157]
Optifine multithread chunk loading is powerful and boost fps a lot. But in boat and MCinabox it crashes. I use 1.7.10, optifine HD u E7 btw.

java.lang.UnsatisfiedLinkError: org.lwjgl.opengl.LinuxPeerInfo.createHandle()Ljava/nio/ByteBuffer;
at org.lwjgl.opengl.LinuxPeerInfo.createHandle(Native Method)
at org.lwjgl.opengl.LinuxPeerInfo.(LinuxPeerInfo.java:44)
at org.lwjgl.opengl.LinuxPbufferPeerInfo.(LinuxPbufferPeerInfo.java:45)
at org.lwjgl.opengl.BoatDisplay.createPbuffer(BoatDisplay.java:244)
at org.lwjgl.opengl.Pbuffer.createPbuffer(Pbuffer.java:234)
at org.lwjgl.opengl.Pbuffer.(Pbuffer.java:219)
at org.lwjgl.opengl.Pbuffer.(Pbuffer.java:190)
at org.lwjgl.opengl.Pbuffer.(Pbuffer.java:166)
at WrUpdaterThreaded.createUpdateThread(WrUpdaterThreaded.java:63)
at WrUpdaterThreaded.delayedInit(WrUpdaterThreaded.java:45)
at WrUpdaterThreaded.updateRenderers(WrUpdaterThreaded.java:176)
at WrUpdates.updateRenderers(WrUpdates.java:71)
at net.minecraft.client.renderer.RenderGlobal.func_72716_a(RenderGlobal.java:2297)
at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1657)
at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1392)
at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
at net.minecraft.client.main.Main.main(SourceFile:148)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by longjunyu2** [comment]
Got it,I have found a same crash.

**Comment by CosineMath** [comment]
We would work on it
