### ISSUE TITLE
Android 11闪退

### ISSUE THREAD

**Issue by RealHeart** [longjunyu2/MCinaBox#322]

**Comment by gamecss** [comment]
症状?是什么操作导致的崩溃?

**Comment by RealHeart** [comment]
安装后直接打开&nbsp;


&nbsp;真心
1307993674@qq.com



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "gamecss"<notifications@github.com&gt;; 
发送时间: 2020年8月17日(星期一) 中午11:10
收件人: "longjunyu2/MCinaBox"<MCinaBox@noreply.github.com&gt;; 
抄送: " 真心"<1307993674@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [longjunyu2/MCinaBox] Android 11闪退 (#322)





 
症状?是什么操作导致的崩溃?

**Comment by RealHeart** [comment]
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.aof.mcinabox/com.aof.mcinabox.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.aof.mcinabox.launcher.json.SettingJson.getDownloadType()' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3497)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3657)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2104)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:7869)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.aof.mcinabox.launcher.json.SettingJson.getDownloadType()' on a null object reference
	at com.aof.mcinabox.minecraft.DownloadMinecraft.getSourceName(DownloadMinecraft.java:57)
	at com.aof.mcinabox.minecraft.DownloadMinecraft.<init>(DownloadMinecraft.java:29)
	at com.aof.mcinabox.MainActivity.onCreate(MainActivity.java:167)
	at android.app.Activity.performCreate(Activity.java:8079)
	at android.app.Activity.performCreate(Activity.java:8061)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1310)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3470)
	... 11 more

**Comment by RealHeart** [comment]
小米10 MIUI 12 20.8.13 Android 11

**Comment by gamecss** [comment]
确定你的安装包是好的？

**Comment by RealHeart** [comment]
完整 github 0.1.3

**Comment by TSaltedfishKing** [comment]
Android10以上不能运行，，，，
到最后会解决的
建议使用vmos来运行
