### ISSUE TITLE
Crash on boot with the latest release 

### ISSUE THREAD

**Issue by Jokkaj** [longjunyu2/MCinaBox#61]
I am using 1.12.2 minecraft, tried to re-install anything but it just crashes 

![Screenshot_2020-04-14-17-37-54-272_com miui bugreport~2](https://user-images.githubusercontent.com/58168823/79244172-dac7f680-7e76-11ea-821c-56fa018b8007.jpg)

**Comment by gabbosta** [comment]
Mine too

**Comment by josexdxd** [comment]
same to me

**Comment by Jokkaj** [comment]
Tried 1.7.10 and 1.15.2 but nothing

**Comment by szarik001** [comment]
Same issue. No matter the version the app just crashes.
Here my crash log:
```
time: 1586913090942
msg: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.aof.mcinabox-FCnelktFR5RPEH224eEe1w==/base.apk"],nativeLibraryDirectories=[/data/app/com.aof.mcinabox-FCnelktFR5RPEH224eEe1w==/lib/arm64, /system/fake-libs64, /data/app/com.aof.mcinabox-FCnelktFR5RPEH224eEe1w==/base.apk!/lib/arm64-v8a, /system/lib64, /system/product/lib64]]] couldn't find "libjndcrash.so"
stacktrace: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.aof.mcinabox-FCnelktFR5RPEH224eEe1w==/base.apk"],nativeLibraryDirectories=[/data/app/com.aof.mcinabox-FCnelktFR5RPEH224eEe1w==/lib/arm64, /system/fake-libs64, /data/app/com.aof.mcinabox-FCnelktFR5RPEH224eEe1w==/base.apk!/lib/arm64-v8a, /system/lib64, /system/product/lib64]]] couldn't find "libjndcrash.so"
	at java.lang.Runtime.loadLibrary0(Runtime.java:1067)
	at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
	at java.lang.System.loadLibrary(System.java:1667)
	at ru.ivanarh.jndcrash.NDCrash.<clinit>(NDCrash.java:199)
	at ru.ivanarh.jndcrash.NDCrash.initializeOutOfProcess(NDCrash.java:58)
	at cosine.boat.LauncherActivity.onCreate(LauncherActivity.java:33)
	at android.app.Activity.performCreate(Activity.java:7824)
	at android.app.Activity.performCreate(Activity.java:7813)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1306)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```
